### ISSUE TITLE
Página inicial del servicio 

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-wizard#10]
Criar a página inicial do serviço e retirar a frase de navegação que está embaixo da caixa de busca.
A sugestão inicial foi criar como uma aba, porém em discussão foi sugerido incluir como um serviço no modelo da Busca avançada ou Localizar descritor de assunto. 

Esta página teria o nome e slogan do serviço,  apresentaria panorama geral do conteúdo, a princípio estático, e uma caixa para navegação do serviço.

**Comment by renatomurasaki** [comment]
Criada página https://bvsalud.org/evideasy/ e botão EVID@Easy no iAHx
