### ISSUE TITLE
Design de navegação

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-wizard#11]
De acordo com reunião realizada, foi solicitado:
Perfeccionar el diseño de la navegación (colores, contraste, letra, etc.)
Exemplo:
Aumentar um pouco a letra
Maior contraste etc.

Prever que mais categorias entrarão na navegação inicial. Ex.: Emergências que já poderá ser incluída após processamento do tema COVID-19

**Comment by marcioalvessilva** [comment]
Forma realizados ajustes no interface do modal
![image](https://user-images.githubusercontent.com/48724136/94157415-998d3700-fe57-11ea-832c-6de368bfa1ca.png)
