### ISSUE TITLE
Acesso ao Wizard a partir da página de divulgação do EVID@Easy - não mostra as opções do step 1

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-wizard#14]
Ao clicar no link 

https://pesquisa.bvsalud.org/portal/?display_wizard=true&lang=es

da página https://bvsalud.org/evideasy/

O EVID@Easy é aberto sem as opções de escolha do passo 1, como mostra imagem abaixo

![image](https://user-images.githubusercontent.com/1226218/109511160-88d59280-7a81-11eb-9c8c-a930390a5820.png)

Ao clicar na caixa correspondente ao passo 1 nada ocorre. Se clicar nas demais caixas se abrem as opções, o que permite clicar novamente na caixa do passo 1 e assim mostrar as opções do Contexto de Saúde.

**Comment by renatomurasaki** [comment]
Essa situação é intermitente.

**Comment by viniciusandrade** [comment]
Ajuste realizado em https://github.com/bireme/iahx-opac/commit/fa87d2294cae72e0ff0e9962108f36b4a3a6ea43.

@renatomurasaki, quando possível, favor limpar cache e realizar novo teste para verificar se o problema persiste.

Obrigado

**Comment by renatomurasaki** [comment]
@viniciusandrade resolvido! Obrigado! Realmente o wizard se perdia qdo saia do passo-a-passo. Com o botão de fechar resolveu o problema.

**Comment by viniciusandrade** [comment]
OK, obrigado por validar.
