### ISSUE TITLE
Doenças Transmissíveis - Evid@Easy - labels nos 4 idiomas

### ISSUE THREAD

**Issue by botturam** [bireme/iahx-wizard#16]
@pintoros segue o arquivo para tradução dos labels das 35 Doençãs Transmissíveis (tarja amarela) para criação dos nomes nos 4 idiomas. 

[traducao-labels-police-makers_TD4.xlsx](https://github.com/bireme/iahx-wizard/files/6964746/traducao-labels-police-makers_TD4.xlsx)

**Comment by pintoros** [comment]
Segue o arquivo com as traduções.
[traducao-labels-police-makers_TD4.xlsx](https://github.com/bireme/iahx-wizard/files/6969634/traducao-labels-police-makers_TD4.xlsx)

**Comment by viniciusandrade** [comment]
@marcoslmori usando o Excel disponibilizado pela Rose favor adicionar traduções no Portal para o bloco (tarja amarela) DOENÇAS TRANSMISSÍVEIS  para o filtro tag_tema_saude.
 
Qualquer dúvida favor entrar em contato. 

Obrigado

**Comment by marcoslmori** [comment]
Feito em instancia de teste. validar!

**Comment by renatomurasaki** [comment]
@marcoslmori favor revisar a tradução do contexto, vide imagem abaixo (todos os idiomas estão assim)

![image](https://user-images.githubusercontent.com/1226218/129396565-f943e0e7-d6de-49a2-ad6d-7183824997d9.png)

**Comment by pintoros** [comment]
1) manter  a primeira de cada palavra do termo em letra maiuscula (corrigido no arquivo )
2) o 1o nível aparece 4TD - Precisa substituir pelo número da meta e nome de acordo título da planilha
3) interface em pt aparece label em inglês
4) demais interfaces es,en, aparece misturado com outros termos

Favor solicitar validação com Verônica na próxima versão.

**Comment by marcoslmori** [comment]
item 1 em pt  e 3 corrigidos

os outros estou checando!

**Comment by marcoslmori** [comment]
item 1 em inglês corrigido
4 - revisado em inglês

**Comment by marcoslmori** [comment]
item 1 em espanhol corrigido
item 4 não encontrei nenhum item em outro idioma, me informe se encontrar para corrigir

**Comment by marcoslmori** [comment]
item 1 em Frances corrigido. Favor validar

**Comment by marcoslmori** [comment]
> 2. o 1o nível aparece 4TD - Precisa substituir pelo número da meta e nome de acordo título da planilha
- Ajustado.  Validar

**Comment by marcoslmori** [comment]
> 4. demais interfaces es,en, aparece misturado com outros termos

Por favor, @pintoros, simulamos e não conseguimos identificar o mesmo comportamento.  Faça um teste completo começando e iniciando no mesmo idioma.

Caso ocorra novamente, por favor, Faça um print screen e cole aqui

**Comment by marcoslmori** [comment]
para que trabalhemos somente em um arquivo excell, coloquei no sharepoint. 

https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/Processamento/evideasy/traducao-labels-police-makers_TD4.CORRIGIDO-mori.xlsx?d=wce9c0454fe2641718101244492a176c4&csf=1&web=1&e=2vwzXw

**Comment by renatomurasaki** [comment]
@marcoslmori @viniciusandrade o erro que a @pintoros reporta eu também identifiquei e ocorre em qualquer contexto. Para simular basta seguir os seguintes passos:

1) Clicar no botão Evid@Easy
2) Escolher um contexto para pode ir para o próximo passo
3) Fechar o Evid@Easy e escolher outro idioma da interface iAHx
4) Clicar no botão Evid@Easy
5) Perceba que o contexto está preenchido e clique no comboBox do tema e verá que todos os temas aparecerão na lista

Hipótese: a lista de temas está perdendo o filtro do contexto de saúde. Se você escolher outro contexto, verá que a lista de temas está correta.

**Comment by marcoslmori** [comment]
solicitado sincronizar os arquivos texts.ini da teste para a produção para o ITI (ocomon 8134) http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=8134&id=q7lu1CbFSJ/AIE4BtVFynAnAERE=

**Comment by viniciusandrade** [comment]
> @marcoslmori @viniciusandrade o erro que a @pintoros reporta eu também identifiquei e ocorre em qualquer contexto. Para simular basta seguir os seguintes passos:
> 
> 1. Clicar no botão Evid@Easy
> 2. Escolher um contexto para pode ir para o próximo passo
> 3. Fechar o Evid@Easy e escolher outro idioma da interface iAHx
> 4. Clicar no botão Evid@Easy
> 5. Perceba que o contexto está preenchido e clique no comboBox do tema e verá que todos os temas aparecerão na lista
> 
> Hipótese: a lista de temas está perdendo o filtro do contexto de saúde. Se você escolher outro contexto, verá que a lista de temas está correta.

Aberto issue #19 para este tema.
