### ISSUE TITLE
Ativar o Evid@Easy no idioma francês, colocando os labels no idioma inglês, até obtermos a respectiva tradução.

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-wizard#17]

**Comment by viniciusandrade** [comment]
Opção Evid@Easy  ativo para o idioma francês.

@marcoslmori favor copiar os blocos de tradução referentes ao Evid@Easy  do texts.ini em inglês para o texts.ini em francês.

**Comment by marcoslmori** [comment]
feito a copia nos componentes
Health context
health subjetc
wizard

Validar e informar se pode colocar em produção

**Comment by renatomurasaki** [comment]
@viniciusandrade @marcoslmori obrigado. Pode colocar em produção.

**Comment by marcoslmori** [comment]
chamado aberto  (8138) http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=8138&id=hkQ1rzSF8v2DLmzjrjlLn+MzAr4=
