### ISSUE TITLE
Mostrar a lista de contextos e temas de saúde em ordem alfabética

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/iahx-wizard#18]

**Comment by viniciusandrade** [comment]
Implementado em https://github.com/bireme/iahx-opac/commit/955305a22bceac0e8aeb67aa18b0bbd3efd731e5

@renatomurasaki quando puder validar o ajuste esta disponível no ambiente de testes. 

Obs. Ainda não existem traduções para os temas do contexto ODS3 - Mortalidade Materna

**Comment by renatomurasaki** [comment]
está correto, @viniciusandrade. Obrigado

**Comment by viniciusandrade** [comment]
Ajuste em produção.
