### ISSUE TITLE
ODS3 - Reduzir a Mortalidade Materna - Evid@Easy - labels nos 4 idiomas

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-wizard#20]
@marcoslmori favor adicionar as traduções nos 4 idiomas que estão do Excel abaixo:

https://paho.sharepoint.com/:x:/r/sites/BIR/TC/TC/Processos/Processamento/evideasy/traducao-labels-police-makers_TD4.CORRIGIDO-mori.xlsx?d=wce9c0454fe2641718101244492a176c4&csf=1&web=1&e=2vwzXw

Na seção **ODS3 - Tema 1 - Reduzir a Mortalidade Materna** onde a 1o coluna é referente ao nome lógico do tema no filtro.

Obrigado.

Issue relacionado: https://github.com/bireme/db-processing/issues/591

**Comment by renatomurasaki** [comment]
@marcoslmori favor verificar este issue, pois já está em produção. Referente aos issues #591 #592 #593 #594 #595

**Comment by marcoslmori** [comment]
traduzido o cluster tag_tema_saude em pt/es/en.  Em Francês foi repetido a tradução em inglês

@botturam  preciso do nome lógico para o cluster de tag_contexto para ODS3 - Reduzir a Mortalidade Materna

**Comment by renatomurasaki** [comment]
@marcoslmori corrigir o contexto

DE: ODS3 - Mortalidade Materna

PARA: ODS3 - Tema 1 - Reduzir a Mortalidade Materna

Alterar 

DE: ODS 3 - Saúde e Bem Estar
PARA: ODS 3 - Demais metas em Saúde e Bem Estar

**Comment by marcoslmori** [comment]
feito!  validar

**Comment by renatomurasaki** [comment]
@marcoslmori obrigado. pode colocar em produção

**Comment by marcoslmori** [comment]
ok

**Comment by marcoslmori** [comment]
chamado aberto no ocomon http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=8149&id=H2XuUhOOvZWOqNtaScJ2wDr12kk=
