### ISSUE TITLE
ODS3 - Outras Metas - Evid@Easy

### ISSUE THREAD

**Issue by botturam** [bireme/iahx-wizard#21]
@viniciusandrade  Estão disponíveis também os conteúdos dos campos "tag_contexto" e "tag_tema_saude" com conteúdo para "Outras Metas".

\<field name="tag_contexto">6_ODS3_demais_metas\</field>
\<field name="tag_tema_saude">6_accidentes_transito.sch\</field>
\<field name="tag_tema_saude">6_cobertura_universal\</field>
\<field name="tag_tema_saude">6_enfermedades_transmissibles\</field>
\<field name="tag_tema_saude">6_muertes_prematuras_enfermedades_notrasmisibles\</field>
\<field name="tag_tema_saude">6_muertes_prevenibles\</field>
\<field name="tag_tema_saude">6_quimicos_contaminacion\</field>
\<field name="tag_tema_saude">6_salud_sexual_reprodutiva\</field>
\<field name="tag_tema_saude">6_sustancias_psicoativas\</field>

PS: estrutura de dados de todos os tipos de ODS3_Wizard (ao final):
https://github.com/bireme/iahx-wizard/issues/15

**Comment by renatomurasaki** [comment]
@botturam não entendi porque você criou este contexto e temas adicionais se os mesmos já estão disponíveis em ODS3 - Saúde e Bem Estar. Ver abaixo:

![image](https://user-images.githubusercontent.com/1226218/130511091-5472b6cd-9864-44ec-9e4c-fec7cc7246e7.png)

Basta editar os labels de ODS3 - Saúde e Bem Estar para ODS 3 - outras metas, retirando a meta 3.1 do tema deste contexto.

**Comment by botturam** [comment]
@renatomurasaki ok. Já retirei a estrutura citada, no meu post. Já estou gerando os dados novamente. Eu entendi que iria precisar dos dados nessa estrutura de dados.

No final, não preciso fazer nada, certo? É só ajuste na interface..

**Comment by botturam** [comment]
desconsiderar estrutura acima.
