### ISSUE TITLE
Labels de navegação - correção

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-wizard#22]
Favor substituir os labels de navegação do Evid@Easy de acordo com a tabela localizada em:
Cooperação técnica | Projetos | REGIONAL | Evid@Easy | Labels_Navegacao.docx

https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Projetos/REGIONAL/Evid@Easy/Labels_Navegacao.docx?d=w95ed5809373848afbce721f180194ad7&csf=1&web=1&e=xH5IhX

**Comment by pintoros** [comment]
Vinícius, segue o link para os novos labels de navegação para nova interface proposta pelo Júlio.
Como conversamos, alguns dos labels antigos serão omitidos e o resultado final deverá apontar para um ou mais tipos de estudos combinados. Esse ajuste eu farei posteriormente, assim que tivermos a versão atualizada. Por ora só os labels:

https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Projetos/REGIONAL/Evid@Easy/Revisao_navegacao-interface/Labels_Navegacao-Traduzido-16nov%20-%20veronica.docx?d=w2bb2d5aace524489a0bbd394e640016e&csf=1&web=1&e=8fRC7b

Vou confirmar reencaminhando a msg da Verônica caso tenha problema para acessar o link.

Obrigada

**Comment by viniciusandrade** [comment]
@pintoros substituições dos labels realizada na interface atual do Evid@Easy que deve também refletir na nova interface do Julio.

Obs: no arquivo de traduções não foram localizados entradas para substituição das seguintes perguntas que estão na base de dados:

- Você está procurando estudos de incidência?
- Você está procurando guias de prática?
- Você está procurando por ensaios clínicos randomizados?
- Você está procurando estudos qualitativos?

Quando possível favor verificar se esta tudo OK. 
Obrigado.

**Comment by pintoros** [comment]
Tradução OK.
As perguntas acima não serão consideradas na próxima versão, por isso não foram traduzidas.
