### ISSUE TITLE
Analisar e implementar o acesso ao novo serviço do evideasy no IAHx

### ISSUE THREAD

**Issue by marcoslmori** [bireme/iahx-wizard#25]
A nova versão desenvolvida por terceiros está implementada em https://bvsalud.org/evideasy/

Substituir pela nova versão o acesso que está no iahx. 

![image](https://user-images.githubusercontent.com/10047460/232780165-27522fca-eebb-476c-a961-fb41cdc48130.png)

**Comment by viniciusandrade** [comment]
@marcoslmori ajuste realizado e disponível nos ambientes de teste e produção.

**Comment by marcoslmori** [comment]
@viniciusandrade, analisar e ajustar esses itens que @pintoros informou via email em 14/04/2023 

"Nas opções que não estão atualizadas de acordo com o último documento no sharepoint Labels_navegação_atual.docx - (veja no email) aparecem opções que não serão mais utilizadas ou foram corrigidas.
As opções não aparecem de acordo com a pergunta do passo 3 (Rutas para la Opción D), de acordo com a tabela acima, cada opção precisa estar de acordo com seu tópico. Fiz um esquema de cores para facilitar. "
Abraço

**Comment by pintoros** [comment]
@viniciusandrade precisamos desse ajuste com prioridade (**interface é EVID@Easy prioridade do mês de abril**), pois o ferramenta já está na produção.
  
https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Projetos/REGIONAL/Evid@Easy/Labels_navega%C3%A7%C3%A3o_atual.docx?d=waa03e368e2c244659fe1195b81b5b13c&csf=1&web=1&e=BZknyY  (tabela no sharepoint)

Hoje aparecem todas as 16 opções para todas as rutas e devem aparecer da seguinte forma de acordo com a ruta (ver tabela no sharepoint):
Ruta 1 - 4 opções
Ruta 2 - 5 opções
Ruta 3 - 6 opções
Ruta 4 - 1 opção

*Alguns dos novos itens estão sem redirecionamento para resultado no iAHx, esses redirecionamentos serão alterados em todos, não serão mais enviados para o cluster Tipo de Estudos ! Solicitarei o processamento das novas estratégias na próxima semana para substituição)

**Comment by viniciusandrade** [comment]
@pintoros ajustes realizados na tradução e na opções de rota.

Favor validar. Obrigado.

**Comment by pintoros** [comment]
@viniciusandrade a lógica agora está correta, porém foram mantidas as opções que **devem ser excluídas** nas perguntas 1, 2 e 3 conforme imagens - item em vermelho.
Um item em azul na P3 que precisa tradução. 
Assim que fizer esse ajuste, confiro a tradução do PT, ES e EN.

![P1](https://user-images.githubusercontent.com/29313904/234941202-77892685-3ee3-495e-9966-1b61f59e1a71.JPG)

![P2](https://user-images.githubusercontent.com/29313904/234941224-25613276-ba28-4dbb-9fe9-4248b4a56dcd.JPG)

![P3](https://user-images.githubusercontent.com/29313904/234941243-4c75ef1d-ea95-442c-bb94-eea172871f7f.JPG)

**Comment by viniciusandrade** [comment]
@pintoros OK, ajustes aplicados.

**Comment by pintoros** [comment]
@viniciusandrade Navegação OK em todos os idiomas.
Apenas 2 problemas com tradução no FrancÊs, acredito que seja com o @marcoslmori 

![image](https://user-images.githubusercontent.com/29313904/235217619-b4fa1269-1db5-4a41-89fa-87b8d2624de5.png)
Aqui falta a tradução dos ODS 3.6 e 3.7


![image](https://user-images.githubusercontent.com/29313904/235217017-f5cff96b-8fad-42ed-86ff-dc36a49db9ba.png)

**Comment by marcoslmori** [comment]
Ok, logo que ajustar informarei

**Comment by marcoslmori** [comment]
Feito as traduções restantes e solicitado ao iti para sincronizar 

chamado: 9169

**Comment by viniciusandrade** [comment]
Acredito que esta ação esteja concluída. Caso falte algo favo re-abrir e informar.
