### ISSUE TITLE
Página Sobre na interface EVID@Easy  (Projeto prioritário Abril/23)

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-wizard#27]
@marcioalvessilva de acordo com a reunião de encaminhamentos segue o arquivo com conteúdo em construção e a estrutura do "Sobre" que deverá estar disponível na página do EVID@Easy nos 4 idiomas.  
[Sobre_em revisão.docx](https://github.com/bireme/iahx-wizard/files/11286400/Sobre_em.revisao.docx)

https://bvsalud.org/evideasy/  - Sobre
https://bvsalud.org/evideasy/pt - Sobre 
https://bvsalud.org/evideasy/en - About
https://bvsalud.org/evideasy/fr - À propos

**Comment by marcioalvessilva** [comment]
Em produção!
