### ISSUE TITLE
Nome do serviço

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-wizard#7]
Incluir o nome EVID@Easy para identificar o serviço.

**Comment by marcioalvessilva** [comment]
Identificação inserida:
No botão
![image](https://user-images.githubusercontent.com/48724136/94156272-4a92d200-fe56-11ea-9019-db0b942c3411.png)

No todo do modal
![image](https://user-images.githubusercontent.com/48724136/94156306-55e5fd80-fe56-11ea-939e-833f56529023.png)
