### ISSUE TITLE
Slogan do serviço

### ISSUE THREAD

**Issue by pintoros** [bireme/iahx-wizard#9]
Quando houver um espaço apropriado, incluir o slogan abaixo do nome:
Busca de evidências guiada
Búsqueda de evidencias guiada
Guided evidence search
Recherche guidée de preuves

**Comment by marcioalvessilva** [comment]
Slogan Inserido
No Modal
![image](https://user-images.githubusercontent.com/48724136/94156756-d1e04580-fe56-11ea-926e-191d5584eb35.png)

Mouse sobre botão
![image](https://user-images.githubusercontent.com/48724136/94157002-1966d180-fe57-11ea-8458-e126a8ef6099.png)
